### ISSUE TITLE
dataset link 

### ISSUE THREAD

**Issue by WilledgeR** [ypwhs/baiduyun_deeplearning_competition#2]
Hi ,

I couldn't download the dataset at https://pan.baidu.com/s/1geT4z9x

Would you please give me another link?

**Comment by WilledgeR** [comment]
Sorry about the issue, forget it :)

**Comment by QQ2737499951** [comment]
请问楼主有决赛的数据集下载吗？学习一下，谢谢

**Comment by WilledgeR** [comment]
First of all learn to speak English like a kid.
Secondly why did you push your codes here? do you know what github is used for?
And finally as i mentioned forget my request. Hard to understand?

**Comment by ypwhs** [comment]
链接: https://pan.baidu.com/s/1op106Ipjc4RtynKulAvGFw 提取码: 64y4

**Comment by shanhedian2017** [comment]
百度网盘链接又失效了

**Comment by 625781186** [comment]
谁还有数据集不

**Comment by QQ2737499951** [comment]
这是来自AAAAAAAAAAAAAA
